"""
Cloud Function: Load audit logs from Cloud Storage to BigQuery
Triggered by: Cloud Storage finalizeCreate event on hapai-audit-* buckets
"""

import json
import logging
import re
from datetime import datetime
from typing import Dict, List, Any
from google.cloud import storage
from google.cloud import bigquery
from google.cloud.exceptions import GoogleCloudError

# Initialize clients
storage_client = storage.Client()
bigquery_client = bigquery.Client()

# Configuration
PROJECT_ID = bigquery_client.project
DATASET_ID = "hapai_dataset"
TABLE_ID = "events"

# Validation patterns
VALID_PROJECT_ID_PATTERN = re.compile(r"^[a-z0-9\-]{6,30}$")
VALID_BUCKET_PATTERN = re.compile(r"^[a-z0-9\-]{3,63}$")
VALID_IDENTIFIER_PATTERN = re.compile(r"^[a-zA-Z_][a-zA-Z0-9_]*$")

# BigQuery schema
# event_id is the deduplication key — generated by audit_log() in _lib.sh as:
#   <epoch_ms>-<hook_name>-<rand4hex>
# All MERGE operations key on event_id to prevent duplicate rows.
# context RECORD holds structured hook-specific analytics fields (added in v1.1.0).
SCHEMA = [
    bigquery.SchemaField("event_id", "STRING", mode="NULLABLE"),  # dedup key; nullable for legacy rows
    bigquery.SchemaField("ts", "TIMESTAMP", mode="REQUIRED"),
    bigquery.SchemaField("event", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("hook", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("tool", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("result", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("reason", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("project", "STRING", mode="NULLABLE"),
    bigquery.SchemaField("context", "RECORD", mode="NULLABLE", fields=[
        bigquery.SchemaField("git_op",                "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("target_branch",         "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("protection_type",       "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("enforcement_method",    "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("filename",              "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("file_category",         "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("file_fullpath",         "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("bypass_method",         "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("protection_source",     "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("was_symlink",           "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("matched_pattern",       "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("risk_category",         "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("command_preview",       "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("files_staged_count",    "INTEGER", mode="NULLABLE"),
        bigquery.SchemaField("packages_touched_count","INTEGER", mode="NULLABLE"),
        bigquery.SchemaField("max_files_threshold",   "INTEGER", mode="NULLABLE"),
        bigquery.SchemaField("max_packages_threshold","INTEGER", mode="NULLABLE"),
        bigquery.SchemaField("packages_list",         "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("was_cooldown_escalation","STRING", mode="NULLABLE"),
        bigquery.SchemaField("enforcement",           "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("forbidden_pattern",     "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("pattern_source",        "STRING",  mode="NULLABLE"),
        bigquery.SchemaField("commit_msg_length",     "INTEGER", mode="NULLABLE"),
    ]),
]

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


def validate_identifier(identifier: str, identifier_type: str = "identifier") -> bool:
    """Validate BigQuery identifiers (dataset, table names)"""
    if not identifier or not isinstance(identifier, str):
        logger.warning(f"Invalid {identifier_type}: not a string")
        return False
    if len(identifier) > 1024:
        logger.warning(f"Invalid {identifier_type}: too long")
        return False
    if not VALID_IDENTIFIER_PATTERN.match(identifier):
        logger.warning(f"Invalid {identifier_type}: invalid characters")
        return False
    return True


def validate_bucket_name(bucket_name: str) -> bool:
    """Validate Cloud Storage bucket name format"""
    if not bucket_name or not isinstance(bucket_name, str):
        logger.warning("Invalid bucket name: not a string")
        return False
    # Bucket names must be 3-63 chars, lowercase, alphanumeric, hyphens
    if not VALID_BUCKET_PATTERN.match(bucket_name):
        logger.warning(f"Invalid bucket name format: {bucket_name[:50]}")
        return False
    return True


def ensure_dataset_and_table(project_id: str) -> str:
    """
    Ensure BigQuery dataset and table exist with proper schema.
    Returns the full table ID.
    """
    dataset_ref = f"{project_id}.{DATASET_ID}"
    table_ref = f"{dataset_ref}.{TABLE_ID}"

    # Check and create dataset if needed
    try:
        bigquery_client.get_dataset(dataset_ref)
        logger.info(f"Dataset {dataset_ref} exists")
    except Exception as e:
        logger.info(f"Creating dataset {dataset_ref}: {e}")
        dataset = bigquery.Dataset(dataset_ref)
        dataset.location = "US"
        bigquery_client.create_dataset(dataset, timeout=30)

    # Check and create table if needed
    try:
        bigquery_client.get_table(table_ref)
        logger.info(f"Table {table_ref} exists")
    except Exception as e:
        logger.info(f"Creating table {table_ref}: {e}")
        table = bigquery.Table(table_ref, schema=SCHEMA)
        table.time_partitioning = bigquery.TimePartitioning(
            type_=bigquery.TimePartitioningType.DAY,
            field="ts",
            expiration_ms=90 * 24 * 3600 * 1000,  # 90 days
        )
        bigquery_client.create_table(table, timeout=30)

    return table_ref


def load_jsonl_to_bigquery(
    bucket_name: str, file_path: str, table_id: str
) -> int:
    """
    Load JSONL file from Cloud Storage to BigQuery with deduplication.

    Dedup strategy (defense-in-depth):
    1. Within the batch: keep only the first occurrence of each event_id.
    2. Against BigQuery: use a MERGE statement keyed on event_id so rows
       that already exist in the table are ignored (WHEN NOT MATCHED INSERT).
    Legacy rows without event_id fall back to streaming insert (no dedup possible).

    Returns the number of rows inserted.
    """
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(file_path)

    logger.info(f"Reading {file_path} from {bucket_name}")

    # Download blob content
    content = blob.download_as_text()

    if not content.strip():
        logger.warning(f"File {file_path} is empty")
        return 0

    # Parse JSONL and prepare rows — deduplicate within batch by event_id
    rows = []
    seen_event_ids: set = set()

    for line_num, line in enumerate(content.strip().split("\n"), 1):
        if not line.strip():
            continue

        try:
            obj = json.loads(line)

            # Validate required fields
            if "ts" not in obj or "event" not in obj:
                logger.warning(f"Line {line_num}: Missing required fields (ts, event)")
                continue

            # Normalize timestamp if needed (ensure RFC 3339 format)
            ts_str = obj.get("ts", "")
            if not ts_str.endswith("Z"):
                ts_str += "Z"

            event_id = obj.get("event_id", "")

            # Batch-level dedup: skip rows with duplicate event_id within this file
            if event_id and event_id in seen_event_ids:
                logger.debug(f"Line {line_num}: Skipping duplicate event_id={event_id}")
                continue
            if event_id:
                seen_event_ids.add(event_id)

            # Build row matching schema — extract _context if present
            raw_ctx = obj.get("_context")
            context = None
            if isinstance(raw_ctx, dict):
                # Map only known schema fields, coerce integer fields
                int_fields = {
                    "files_staged_count", "packages_touched_count",
                    "max_files_threshold", "max_packages_threshold",
                    "commit_msg_length",
                }
                context = {}
                for k, v in raw_ctx.items():
                    if k in int_fields:
                        try:
                            context[k] = int(v)
                        except (TypeError, ValueError):
                            context[k] = None
                    elif isinstance(v, str):
                        context[k] = v[:500]  # cap string fields
                    elif v is None:
                        context[k] = None

            row = {
                "event_id": event_id,
                "ts": ts_str,
                "event": obj.get("event", ""),
                "hook": obj.get("hook", ""),
                "tool": obj.get("tool", ""),
                "result": obj.get("result", ""),
                "reason": obj.get("reason", ""),
                "project": obj.get("project", ""),
                "context": context,
            }
            rows.append(row)

        except json.JSONDecodeError as e:
            logger.warning(f"Line {line_num}: Invalid JSON: {e}")
            continue

    if not rows:
        logger.warning(f"No valid rows found in {file_path}")
        return 0

    # Split into rows with event_id (can use MERGE dedup) and legacy rows (streaming insert)
    # Note: context field is passed through as-is (None or dict) — BigQuery handles RECORD serialization
    rows_with_id = [r for r in rows if r.get("event_id")]
    rows_legacy  = [r for r in rows if not r.get("event_id")]

    inserted = 0

    # ── MERGE path: idempotent upsert keyed on event_id ──────────────────────
    if rows_with_id:
        inserted += _merge_rows_by_event_id(rows_with_id, table_id)

    # ── Legacy path: direct streaming insert (no dedup, best-effort) ─────────
    if rows_legacy:
        logger.info(f"Inserting {len(rows_legacy)} legacy rows (no event_id) via streaming insert")
        errors = bigquery_client.insert_rows_json(table_id, rows_legacy, timeout=30)
        if errors:
            logger.error(f"BigQuery streaming insert errors: {errors}")
        else:
            inserted += len(rows_legacy)

    logger.info(f"Loaded {inserted}/{len(rows)} rows into {table_id}")
    return inserted


def _merge_rows_by_event_id(rows: List[Dict], table_id: str) -> int:
    """
    Insert rows idempotently using streaming insert + dedup-at-query-time strategy.

    Strategy (context RECORD makes inline MERGE SQL impractical):
    1. Filter out rows whose event_id already exists in BigQuery (pre-check query).
    2. Insert only new rows via insert_rows_json (handles RECORD/nested fields natively).
    3. The _dedup_cte() in query layer handles any remaining duplicates at read time.

    For batches > 500 rows, splits into chunks.
    Returns the number of rows inserted.
    """
    BATCH_LIMIT = 500

    if len(rows) > BATCH_LIMIT:
        total = 0
        for i in range(0, len(rows), BATCH_LIMIT):
            total += _merge_rows_by_event_id(rows[i:i + BATCH_LIMIT], table_id)
        return total

    # Pre-check: which event_ids already exist in BigQuery?
    event_ids = [r["event_id"] for r in rows if r.get("event_id")]
    existing_ids: set = set()

    if event_ids:
        try:
            id_list = ", ".join(f"'{eid}'" for eid in event_ids[:500])
            check_sql = f"""
                SELECT event_id FROM `{table_id}`
                WHERE event_id IN ({id_list})
            """
            result = bigquery_client.query(check_sql).result(timeout=30)
            existing_ids = {row["event_id"] for row in result}
            if existing_ids:
                logger.info(f"Pre-check: {len(existing_ids)} event_ids already exist, skipping them")
        except Exception as e:
            logger.warning(f"Pre-check query failed (will insert all): {e}")

    new_rows = [r for r in rows if r.get("event_id") not in existing_ids]

    if not new_rows:
        logger.info("All rows already exist in BigQuery — nothing to insert")
        return 0

    errors = bigquery_client.insert_rows_json(table_id, new_rows, timeout=30)
    if errors:
        logger.error(f"BigQuery insert errors: {errors}")
        return 0

    logger.info(f"Inserted {len(new_rows)}/{len(rows)} rows ({len(existing_ids)} skipped as duplicates)")
    return len(new_rows)


def load_audit_from_gcs(cloud_event):
    """
    Cloud Function entry point (Gen2 / Eventarc CloudEvent format).
    Triggered by: gs://hapai-audit-*/**.jsonl (Eventarc/Cloud Storage)
    """
    # Gen2 Eventarc delivers a CloudEvent object; data is in cloud_event.data
    if hasattr(cloud_event, "data"):
        data = cloud_event.data
    elif isinstance(cloud_event, dict):
        data = cloud_event
    else:
        logger.error(f"Unexpected event type: {type(cloud_event)}")
        return {"status": "error", "message": "Unexpected event format"}

    logger.info(f"Received event data: {json.dumps(data)}")

    # Parse trigger metadata
    bucket_name = data.get("bucket")
    file_path = data.get("name")

    if not bucket_name or not file_path:
        logger.error("Missing bucket or file path in event")
        return {"status": "error", "message": "Invalid event"}

    # Validate file type
    if not file_path.endswith(".jsonl"):
        logger.info(f"Skipping non-JSONL file: {file_path}")
        return {"status": "skipped", "message": "Not a JSONL file"}

    try:
        # Infer project ID from bucket name
        # Bucket naming convention: hapai-audit-{username}
        # GCP project can be inferred from the storage bucket's project
        project_id = bigquery_client.project

        # Ensure dataset and table exist
        table_id = ensure_dataset_and_table(project_id)

        # Load audit log
        rows_loaded = load_jsonl_to_bigquery(bucket_name, file_path, table_id)

        return {
            "status": "success",
            "message": f"Loaded {rows_loaded} rows",
            "bucket": bucket_name,
            "file": file_path,
            "table": table_id,
        }

    except Exception as e:
        logger.error(f"Error processing {file_path}: {str(e)}", exc_info=True)
        return {"status": "error", "message": str(e)}


def load_audit_logs(request):
    """
    HTTP entry point for Cloud Functions.
    For testing/health checks only.
    Real trigger is Eventarc on Cloud Storage.
    """
    return {"status": "ok", "message": "Cloud Function is running"}


# ─── BigQuery Query Proxy ──────────────────────────────────────────────────────

import firebase_admin
from firebase_admin import auth as firebase_auth
import functions_framework

if not firebase_admin._apps:
    firebase_admin.initialize_app()

_ALLOWED_ORIGINS = {
    "https://hapai.oute.pro",
    "https://renatobardi.github.io",
}


def _get_table_ref(table_name: str) -> str:
    """Get parameterized table reference using current project ID."""
    return f"`{PROJECT_ID}.{DATASET_ID}.{table_name}`"


def _validate_period(body: dict) -> int:
    """Validate period param. Returns 7, 14, or 30 (default 30)."""
    period = body.get("period", 30)
    try:
        period = int(period)
    except (TypeError, ValueError):
        return 30
    return period if period in (7, 14, 30) else 30


def _validate_safe_string(value, max_len: int = 100):
    """Validate a string for use as a BigQuery query parameter."""
    if not value or not isinstance(value, str):
        return None
    value = value.strip()
    if not value or len(value) > max_len:
        return None
    return value


def _validate_limit(body: dict, default: int = 100) -> int:
    limit = body.get("limit", default)
    try:
        limit = int(limit)
    except (TypeError, ValueError):
        return default
    return max(10, min(200, limit))


def _validate_offset(body: dict) -> int:
    offset = body.get("offset", 0)
    try:
        offset = int(offset)
    except (TypeError, ValueError):
        return 0
    return max(0, min(10000, offset))


def _run_query(sql: str, params=None) -> list:
    """Run a BigQuery query, optionally with parameterized inputs."""
    job_config = bigquery.QueryJobConfig(query_parameters=params) if params else None
    result = bigquery_client.query(sql, job_config=job_config).result()
    return [dict(row) for row in result]


def _dedup_cte_with_context(ref: str, period: int) -> str:
    """
    Extended dedup CTE that includes the context RECORD for analytics queries.
    """
    return f"""
        WITH deduped AS (
          SELECT
            event_id, ts, event, hook, tool, result, reason, project, context,
            ROW_NUMBER() OVER (
              PARTITION BY COALESCE(NULLIF(event_id, ''), CAST(ts AS STRING) || hook || tool || result)
              ORDER BY ts ASC
            ) AS _rn
          FROM {ref}
          WHERE ts >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL {period} DAY)
        )
    """


def _dedup_cte(ref: str, period: int) -> str:
    """
    Returns a WITH clause that deduplicates rows by event_id.

    Strategy:
    - Rows WITH event_id: keep only one row per event_id (pick the earliest ts).
      This handles any duplicates that slipped past the MERGE (e.g. legacy rows
      re-ingested before P3 was deployed, or rows from the bq CLI load path).
    - Rows WITHOUT event_id (legacy): deduplicated by composite key (ts, hook, tool, result).
      For each unique combination of these fields, keeps only the earliest row.

    Usage: prefix your query with _dedup_cte(ref, period) and query `deduped` instead
    of the raw table.
    """
    return f"""
        WITH deduped AS (
          SELECT
            event_id, ts, event, hook, tool, result, reason, project,
            ROW_NUMBER() OVER (
              PARTITION BY COALESCE(NULLIF(event_id, ''), CAST(ts AS STRING) || hook || tool || result)
              ORDER BY ts ASC
            ) AS _rn
          FROM {ref}
          WHERE ts >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL {period} DAY)
        )
    """


def _query_stats(period: int) -> list:
    ref = _get_table_ref(TABLE_ID)
    sql = f"""
        {_dedup_cte(ref, period)}
        SELECT
          COUNTIF(result = 'deny')        AS denials,
          COUNTIF(result = 'warn')        AS warnings,
          COUNTIF(result = 'allow')       AS allow_count,
          CAST(COUNT(*) AS INT64)         AS total_events
        FROM deduped
        WHERE _rn = 1
    """
    return _run_query(sql)


def _query_timeline(period: int) -> list:
    ref = _get_table_ref(TABLE_ID)
    sql = f"""
        {_dedup_cte(ref, period)}
        SELECT
          FORMAT_DATE('%Y-%m-%d', DATE(ts)) AS day,
          result                            AS event,
          CAST(COUNT(*) AS INT64)           AS count
        FROM deduped
        WHERE _rn = 1
          AND result IN ('allow', 'deny', 'warn')
        GROUP BY day, result
        ORDER BY day
    """
    return _run_query(sql)


def _query_hooks(period: int) -> list:
    ref = _get_table_ref(TABLE_ID)
    sql = f"""
        {_dedup_cte(ref, period)}
        SELECT
          hook,
          CAST(COUNT(*) AS INT64) AS blocks
        FROM deduped
        WHERE _rn = 1
          AND result = 'deny'
        GROUP BY hook
        ORDER BY blocks DESC
        LIMIT 10
    """
    return _run_query(sql)


def _query_tools(period: int) -> list:
    ref = _get_table_ref(TABLE_ID)
    sql = f"""
        {_dedup_cte(ref, period)}
        SELECT
          tool,
          CAST(COUNT(*) AS INT64) AS count
        FROM deduped
        WHERE _rn = 1
          AND result = 'deny'
        GROUP BY tool
        ORDER BY count DESC
    """
    return _run_query(sql)


def _query_projects(period: int) -> list:
    ref = _get_table_ref(TABLE_ID)
    sql = f"""
        {_dedup_cte(ref, period)}
        SELECT
          project,
          CAST(COUNT(*) AS INT64) AS count
        FROM deduped
        WHERE _rn = 1
          AND result = 'deny'
          AND project IS NOT NULL
        GROUP BY project
        ORDER BY count DESC
        LIMIT 10
    """
    return _run_query(sql)


def _query_denials(
    limit: int,
    offset: int,
    event_filter: str = None,
    hook_filter: str = None,
    tool_filter: str = None,
) -> list:
    ref = _get_table_ref(TABLE_ID)
    # _dedup_cte already filters by period; for denials we use a large window (90d)
    inner_where = ["result IN ('deny', 'warn')", "_rn = 1"]
    params: List[Any] = []

    if event_filter:
        inner_where.append("result = @event_filter")
        params.append(bigquery.ScalarQueryParameter("event_filter", "STRING", event_filter))
    if hook_filter:
        inner_where.append("hook = @hook_filter")
        params.append(bigquery.ScalarQueryParameter("hook_filter", "STRING", hook_filter))
    if tool_filter:
        inner_where.append("tool = @tool_filter")
        params.append(bigquery.ScalarQueryParameter("tool_filter", "STRING", tool_filter))

    params.append(bigquery.ScalarQueryParameter("q_limit",  "INT64", limit))
    params.append(bigquery.ScalarQueryParameter("q_offset", "INT64", offset))

    sql = f"""
        {_dedup_cte(ref, 90)}
        SELECT
          FORMAT_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', ts) AS ts,
          event, hook, tool, result, project
        FROM deduped
        WHERE {" AND ".join(inner_where)}
        ORDER BY ts DESC
        LIMIT @q_limit
        OFFSET @q_offset
    """
    return _run_query(sql, params)


def _query_project_health(period: int) -> list:
    """
    Per-project health: total events, denial rate %, warning rate %, trend.
    Returns projects sorted by denial rate descending.
    """
    ref = _get_table_ref(TABLE_ID)
    sql = f"""
        {_dedup_cte(ref, period)}
        SELECT
          project,
          CAST(COUNT(*) AS INT64)                              AS total_events,
          CAST(COUNTIF(result = 'deny') AS INT64)              AS denials,
          CAST(COUNTIF(result = 'warn') AS INT64)              AS warnings,
          CAST(COUNTIF(result = 'allow') AS INT64)             AS allows,
          ROUND(SAFE_DIVIDE(COUNTIF(result = 'deny') * 100.0, COUNT(*)), 1) AS denial_rate,
          ROUND(SAFE_DIVIDE(COUNTIF(result = 'warn') * 100.0, COUNT(*)), 1) AS warning_rate,
          MIN(ts) AS first_seen,
          MAX(ts) AS last_seen
        FROM deduped
        WHERE _rn = 1
          AND project IS NOT NULL
          AND result IN ('deny', 'warn', 'allow')
        GROUP BY project
        HAVING total_events >= 5
        ORDER BY denial_rate DESC
        LIMIT 20
    """
    return _run_query(sql)


def _query_denial_reasons(period: int, hook_filter: str = None) -> list:
    """
    Aggregate denial reasons — most common messages, grouped by hook and reason text.
    Reveals patterns like 'Commit blocked on protected branch main' appearing 80 times.
    """
    ref = _get_table_ref(TABLE_ID)
    where = ["_rn = 1", "result = 'deny'", "reason IS NOT NULL", "reason != ''"]
    params = []

    if hook_filter:
        where.append("hook = @hook_filter")
        params.append(bigquery.ScalarQueryParameter("hook_filter", "STRING", hook_filter))

    sql = f"""
        {_dedup_cte(ref, period)}
        SELECT
          hook,
          reason,
          CAST(COUNT(*) AS INT64) AS count
        FROM deduped
        WHERE {" AND ".join(where)}
        GROUP BY hook, reason
        ORDER BY count DESC
        LIMIT 30
    """
    return _run_query(sql, params if params else None)


def _query_context_breakdown(period: int, hook_filter: str = None) -> dict:
    """
    Context-aware analytics: breakdowns using structured _context fields.
    Returns per-hook breakdowns by category (file_category, risk_category, target_branch, etc.)
    """
    ref = _get_table_ref(TABLE_ID)
    cte = _dedup_cte_with_context(ref, period)
    hook_clause = ""
    params = []

    if hook_filter:
        hook_clause = "AND hook = @hook_filter"
        params.append(bigquery.ScalarQueryParameter("hook_filter", "STRING", hook_filter))

    # File categories blocked
    file_cats = _run_query(f"""
        {cte}
        SELECT
          context.file_category AS category,
          CAST(COUNT(*) AS INT64) AS count
        FROM deduped
        WHERE _rn = 1
          AND result = 'deny'
          AND context.file_category IS NOT NULL
          {hook_clause}
        GROUP BY category ORDER BY count DESC
    """, params if params else None)

    # Risk categories (destructive)
    risk_cats = _run_query(f"""
        {cte}
        SELECT
          context.risk_category AS category,
          CAST(COUNT(*) AS INT64) AS count
        FROM deduped
        WHERE _rn = 1
          AND result = 'deny'
          AND context.risk_category IS NOT NULL
          {hook_clause}
        GROUP BY category ORDER BY count DESC
    """, params if params else None)

    # Target branches blocked
    branches = _run_query(f"""
        {cte}
        SELECT
          context.target_branch AS branch,
          CAST(COUNT(*) AS INT64) AS count
        FROM deduped
        WHERE _rn = 1
          AND result = 'deny'
          AND context.target_branch IS NOT NULL
          {hook_clause}
        GROUP BY branch ORDER BY count DESC LIMIT 10
    """, params if params else None)

    # Git operations blocked
    git_ops = _run_query(f"""
        {cte}
        SELECT
          context.git_op AS op,
          CAST(COUNT(*) AS INT64) AS count
        FROM deduped
        WHERE _rn = 1
          AND result = 'deny'
          AND context.git_op IS NOT NULL
          {hook_clause}
        GROUP BY op ORDER BY count DESC
    """, params if params else None)

    # Forbidden patterns (commit-msg)
    commit_patterns = _run_query(f"""
        {cte}
        SELECT
          context.forbidden_pattern AS pattern,
          CAST(COUNT(*) AS INT64) AS count
        FROM deduped
        WHERE _rn = 1
          AND result = 'deny'
          AND context.forbidden_pattern IS NOT NULL
          {hook_clause}
        GROUP BY pattern ORDER BY count DESC LIMIT 10
    """, params if params else None)

    return {
        "file_categories": file_cats,
        "risk_categories": risk_cats,
        "blocked_branches": branches,
        "git_ops": git_ops,
        "commit_patterns": commit_patterns,
    }


def _query_stats_comparison(period: int) -> list:
    """
    Stats for current period AND previous period of equal length — enables trend vs. previous period.
    Returns two rows: current and previous.
    """
    ref = _get_table_ref(TABLE_ID)
    sql = f"""
        WITH all_events AS (
          SELECT
            event_id, ts, hook, tool, result,
            ROW_NUMBER() OVER (
              PARTITION BY COALESCE(NULLIF(event_id, ''), CAST(ts AS STRING) || hook || tool || result)
              ORDER BY ts ASC
            ) AS _rn
          FROM {ref}
          WHERE ts >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL {period * 2} DAY)
        ),
        deduped AS (SELECT * FROM all_events WHERE _rn = 1)
        SELECT
          CASE
            WHEN ts >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL {period} DAY)
            THEN 'current'
            ELSE 'previous'
          END AS period_label,
          CAST(COUNT(*) AS INT64)                                        AS total_events,
          CAST(COUNTIF(result = 'deny') AS INT64)                        AS denials,
          CAST(COUNTIF(result = 'warn') AS INT64)                        AS warnings,
          ROUND(SAFE_DIVIDE(COUNTIF(result = 'deny') * 100.0, COUNT(*)), 1) AS denial_rate,
          ROUND(SAFE_DIVIDE(COUNTIF(result = 'warn') * 100.0, COUNT(*)), 1) AS warning_rate
        FROM deduped
        WHERE result IN ('deny', 'warn', 'allow')
        GROUP BY period_label
    """
    return _run_query(sql)


def _query_hook_detail(hook_name: str, period: int) -> dict:
    """Mini-timeline + tool breakdown + recent events for a specific guard."""
    ref = _get_table_ref(TABLE_ID)
    p = [bigquery.ScalarQueryParameter("hook_name", "STRING", hook_name)]
    cte = _dedup_cte(ref, period)

    timeline = _run_query(f"""
        {cte}
        SELECT
          FORMAT_DATE('%Y-%m-%d', DATE(ts)) AS day,
          CAST(COUNT(*) AS INT64)           AS count
        FROM deduped
        WHERE _rn = 1
          AND hook = @hook_name
          AND result IN ('deny', 'warn')
        GROUP BY day ORDER BY day
    """, p)

    breakdown = _run_query(f"""
        {cte}
        SELECT
          tool                    AS label,
          CAST(COUNT(*) AS INT64) AS count
        FROM deduped
        WHERE _rn = 1
          AND hook = @hook_name
          AND result IN ('deny', 'warn')
        GROUP BY tool ORDER BY count DESC LIMIT 8
    """, p)

    recent = _run_query(f"""
        {cte}
        SELECT
          FORMAT_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', ts) AS ts,
          event, hook, tool, result, project
        FROM deduped
        WHERE _rn = 1
          AND hook = @hook_name
          AND result IN ('deny', 'warn')
        ORDER BY ts DESC LIMIT 10
    """, p)

    stats_row = _run_query(f"""
        {cte}
        SELECT
          CAST(COUNT(*) AS INT64)                 AS total,
          CAST(COUNTIF(result = 'deny') AS INT64) AS deny_count,
          CAST(COUNTIF(result = 'warn') AS INT64) AS warn_count
        FROM deduped
        WHERE _rn = 1
          AND hook = @hook_name
          AND result IN ('deny', 'warn')
    """, p)

    s = stats_row[0] if stats_row else {"total": 0, "deny_count": 0, "warn_count": 0}
    return {"timeline": timeline, "breakdown": breakdown, "recent": recent, **s}


def _query_tool_detail(tool_name: str, period: int) -> dict:
    """Mini-timeline + hook breakdown + recent events for a specific tool."""
    ref = _get_table_ref(TABLE_ID)
    p = [bigquery.ScalarQueryParameter("tool_name", "STRING", tool_name)]
    cte = _dedup_cte(ref, period)

    timeline = _run_query(f"""
        {cte}
        SELECT
          FORMAT_DATE('%Y-%m-%d', DATE(ts)) AS day,
          CAST(COUNT(*) AS INT64)           AS count
        FROM deduped
        WHERE _rn = 1
          AND tool = @tool_name
          AND result IN ('deny', 'warn')
        GROUP BY day ORDER BY day
    """, p)

    breakdown = _run_query(f"""
        {cte}
        SELECT
          hook                    AS label,
          CAST(COUNT(*) AS INT64) AS count
        FROM deduped
        WHERE _rn = 1
          AND tool = @tool_name
          AND result IN ('deny', 'warn')
        GROUP BY hook ORDER BY count DESC LIMIT 8
    """, p)

    recent = _run_query(f"""
        {cte}
        SELECT
          FORMAT_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', ts) AS ts,
          event, hook, tool, result, project
        FROM deduped
        WHERE _rn = 1
          AND tool = @tool_name
          AND result IN ('deny', 'warn')
        ORDER BY ts DESC LIMIT 10
    """, p)

    stats_row = _run_query(f"""
        {cte}
        SELECT
          CAST(COUNT(*) AS INT64)                 AS total,
          CAST(COUNTIF(result = 'deny') AS INT64) AS deny_count,
          CAST(COUNTIF(result = 'warn') AS INT64) AS warn_count
        FROM deduped
        WHERE _rn = 1
          AND tool = @tool_name
          AND result IN ('deny', 'warn')
    """, p)

    s = stats_row[0] if stats_row else {"total": 0, "deny_count": 0, "warn_count": 0}
    return {"timeline": timeline, "breakdown": breakdown, "recent": recent, **s}


@functions_framework.http
def bq_query(request):
    """
    HTTP endpoint: validates Firebase ID token, runs a named BigQuery query.
    Frontend sends: POST { "query_name": "stats", "period": 30, ... }
    Authorization: Bearer <firebase-id-token>
    """
    origin = request.headers.get("Origin", "")
    allowed_origin = origin if origin in _ALLOWED_ORIGINS else next(iter(_ALLOWED_ORIGINS))
    cors = {"Access-Control-Allow-Origin": allowed_origin}

    if request.method == "OPTIONS":
        return ("", 204, {
            **cors,
            "Access-Control-Allow-Headers": "Authorization, Content-Type",
            "Access-Control-Allow-Methods": "POST",
        })

    auth_header = request.headers.get("Authorization", "") or ""
    if not auth_header.startswith("Bearer "):
        return ({"error": "Unauthorized"}, 401, cors)

    id_token = auth_header[len("Bearer "):]
    try:
        firebase_auth.verify_id_token(id_token)
    except Exception as e:
        logger.warning(f"Token validation failed: {e}")
        return ({"error": "Invalid token"}, 401, cors)

    body = request.get_json(silent=True) or {}
    query_name = body.get("query_name")
    if not query_name:
        return ({"error": "Missing query_name"}, 400, cors)

    period = _validate_period(body)

    try:
        if query_name == "stats":
            result = _query_stats(period)

        elif query_name == "timeline":
            result = _query_timeline(period)

        elif query_name == "hooks":
            result = _query_hooks(period)

        elif query_name == "tools":
            result = _query_tools(period)

        elif query_name == "projects":
            result = _query_projects(period)

        elif query_name == "denials":
            limit  = _validate_limit(body)
            offset = _validate_offset(body)
            event_filter = _validate_safe_string(body.get("event_filter"), max_len=10)
            hook_filter  = _validate_safe_string(body.get("hook_filter"),  max_len=100)
            tool_filter  = _validate_safe_string(body.get("tool_filter"),  max_len=100)
            if event_filter and event_filter not in ("deny", "warn"):
                event_filter = None
            result = _query_denials(limit, offset, event_filter, hook_filter, tool_filter)

        elif query_name == "hook_detail":
            hook_name = _validate_safe_string(body.get("hook_name"))
            if not hook_name:
                return ({"error": "Missing or invalid hook_name"}, 400, cors)
            result = _query_hook_detail(hook_name, period)

        elif query_name == "tool_detail":
            tool_name = _validate_safe_string(body.get("tool_name"))
            if not tool_name:
                return ({"error": "Missing or invalid tool_name"}, 400, cors)
            result = _query_tool_detail(tool_name, period)

        elif query_name == "project_health":
            result = _query_project_health(period)

        elif query_name == "denial_reasons":
            hook_filter = _validate_safe_string(body.get("hook_filter"), max_len=100)
            result = _query_denial_reasons(period, hook_filter)

        elif query_name == "context_breakdown":
            hook_filter = _validate_safe_string(body.get("hook_filter"), max_len=100)
            result = _query_context_breakdown(period, hook_filter)

        elif query_name == "stats_comparison":
            result = _query_stats_comparison(period)

        else:
            return ({"error": f"Unknown query: {query_name}"}, 400, cors)

        return (result, 200, cors)

    except Exception as e:
        logger.error(f"BigQuery query '{query_name}' failed: {e}", exc_info=True)
        return ({"error": "Query failed"}, 500, cors)
