#!/usr/bin/env bash
# hapai/hooks/pre-tool-use/guard-files.sh
# Blocks writes to protected files (.env, lockfiles, CI configs).
# Resolves symlinks via realpath to prevent symlink bypass.
# Event: PreToolUse | Matcher: Write|Edit|MultiEdit | Timeout: 7s

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../_lib.sh"

read_input

tool_name="$(get_tool_name)"
case "$tool_name" in
  Write|Edit|MultiEdit) ;;
  *) exit 0 ;;
esac

# Extract file path
file_path="$(get_field '.tool_input.file_path')"
[[ -z "$file_path" ]] && exit 0

# Check if file protection is enabled
enabled="$(config_get "guardrails.file_protection.enabled" "true")"
[[ "$enabled" != "true" ]] && allow

# Resolve symlinks to prevent bypass (ln -s .env safe.txt → still catches .env)
resolved_path="$file_path"
if command -v realpath &>/dev/null && [[ -e "$file_path" ]]; then
  resolved_path="$(realpath "$file_path" 2>/dev/null || echo "$file_path")"
fi

filename="$(basename "$resolved_path")"

# Check unprotected list first (explicit overrides)
while IFS= read -r pattern; do
  [[ -z "$pattern" ]] && continue
  # shellcheck disable=SC2053
  if [[ "$filename" == $pattern ]]; then
    allow
  fi
done <<< "$(config_get_list "guardrails.file_protection.unprotected")"

# Check against protected patterns
_check_protected() {
  local name="$1" path="$2"

  # .env files (but not .env.example / .env.sample)
  if [[ "$name" == ".env" ]]; then
    deny "hapai: Write blocked — '.env' is a protected file. Environment files should not be modified by AI."
  fi
  if [[ "$name" == .env.* ]] && [[ "$name" != ".env.example" ]] && [[ "$name" != ".env.sample" ]]; then
    deny "hapai: Write blocked — '$name' is a protected environment file."
  fi

  # Lockfiles
  if [[ "$name" == *.lock ]] || [[ "$name" == "package-lock.json" ]] || [[ "$name" == "pnpm-lock.yaml" ]] || [[ "$name" == "poetry.lock" ]] || [[ "$name" == "uv.lock" ]]; then
    deny "hapai: Write blocked — '$name' is a lockfile. Lockfiles should be generated by package managers, not edited directly."
  fi

  # CI/CD workflow files
  if [[ "$path" == *.github/workflows/* ]]; then
    deny "hapai: Write blocked — CI/CD workflow files are protected. Modify workflows manually."
  fi
}

_check_protected "$filename" "$resolved_path"

# Check config-defined protected patterns
while IFS= read -r pattern; do
  [[ -z "$pattern" ]] && continue
  # Already handled above as defaults
  [[ "$pattern" == ".env" || "$pattern" == ".env.*" || "$pattern" == "*.lock" ]] && continue
  [[ "$pattern" == "package-lock.json" || "$pattern" == "pnpm-lock.yaml" ]] && continue
  [[ "$pattern" == "poetry.lock" || "$pattern" == "uv.lock" ]] && continue
  [[ "$pattern" == ".github/workflows/*" ]] && continue

  # Custom patterns: match filename or path
  # shellcheck disable=SC2053
  if [[ "$filename" == $pattern ]] || [[ "$resolved_path" == */$pattern ]]; then
    state_increment "guard-files.deny_count"
    deny "hapai: Write blocked — '$filename' matches protected pattern '$pattern'."
  fi
done <<< "$(config_get_list "guardrails.file_protection.protected")"

allow
