#!/usr/bin/env bash
# hapai/hooks/pre-tool-use/guard-files.sh
# Blocks writes to protected files (.env, lockfiles, CI configs)
# Event: PreToolUse | Matcher: Write|Edit|MultiEdit | Timeout: 7s

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../_lib.sh"

read_input

tool_name="$(get_tool_name)"

# Extract file path based on tool type
file_path=""
case "$tool_name" in
  Write)
    file_path="$(get_field '.tool_input.file_path')"
    ;;
  Edit|MultiEdit)
    file_path="$(get_field '.tool_input.file_path')"
    ;;
  *)
    exit 0
    ;;
esac

[[ -z "$file_path" ]] && exit 0

# Check if file protection is enabled
enabled="$(config_get "guardrails.file_protection.enabled" "true")"
[[ "$enabled" != "true" ]] && allow

# Get the basename and relative path for matching
filename="$(basename "$file_path")"
rel_path="$file_path"

# Check unprotected list first (explicit overrides)
while IFS= read -r pattern; do
  [[ -z "$pattern" ]] && continue
  if [[ "$filename" == $pattern ]] || [[ "$rel_path" == *$pattern ]]; then
    allow
  fi
done <<< "$(config_get_list "guardrails.file_protection.unprotected")"

# Default protected patterns
DEFAULT_PROTECTED=(
  ".env"
  ".env.*"
  "*.lock"
  "package-lock.json"
  "pnpm-lock.yaml"
  "poetry.lock"
  "uv.lock"
)

# Check default patterns
for pattern in "${DEFAULT_PROTECTED[@]}"; do
  case "$pattern" in
    .env)
      if [[ "$filename" == ".env" ]]; then
        state_increment "guard-files.deny_count"
        deny "🛑 hapai: Write blocked — '$filename' is a protected file. Environment files should not be modified by AI."
      fi
      ;;
    .env.*)
      if [[ "$filename" == .env.* ]] && [[ "$filename" != ".env.example" ]] && [[ "$filename" != ".env.sample" ]]; then
        state_increment "guard-files.deny_count"
        deny "🛑 hapai: Write blocked — '$filename' is a protected environment file."
      fi
      ;;
    *.lock|package-lock.json|pnpm-lock.yaml|poetry.lock|uv.lock)
      if [[ "$filename" == *.lock ]] || [[ "$filename" == "package-lock.json" ]] || [[ "$filename" == "pnpm-lock.yaml" ]] || [[ "$filename" == "poetry.lock" ]] || [[ "$filename" == "uv.lock" ]]; then
        state_increment "guard-files.deny_count"
        deny "🛑 hapai: Write blocked — '$filename' is a lockfile. Lockfiles should be generated by package managers, not edited directly."
      fi
      ;;
  esac
done

# Check config-defined protected patterns
while IFS= read -r pattern; do
  [[ -z "$pattern" ]] && continue

  # Glob-style matching
  case "$pattern" in
    .github/workflows/*)
      if [[ "$rel_path" == *.github/workflows/* ]]; then
        state_increment "guard-files.deny_count"
        deny "🛑 hapai: Write blocked — CI/CD workflow files are protected. Modify workflows manually."
      fi
      ;;
    *)
      if [[ "$filename" == $pattern ]] || [[ "$rel_path" == *$pattern ]]; then
        state_increment "guard-files.deny_count"
        deny "🛑 hapai: Write blocked — '$filename' matches protected pattern '$pattern'."
      fi
      ;;
  esac
done <<< "$(config_get_list "guardrails.file_protection.protected")"

allow
